version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder
        user: builder
    working_directory: ~/src
  infrastructure:
    docker:
      - image: aeternity/infrastructure:stable
    working_directory: ~/src

jobs:
  build:
    executor: aebuilder
    steps:
      - checkout
      - run:
          name: Build
          command: ./bootstrap
      - run:
          name: Common Tests
          command: ./rebar3 ct
      - store_artifacts:
          path: rebar3
      - persist_to_workspace:
          root: .
          paths: [rebar3]
  publish:
    executor: infrastructure
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload release
          command: |
            /infrastructure/scripts/upload-github-release-assets.sh github_api_token=${GITHUB_API_TOKEN:?} \
              owner=${CIRCLE_PROJECT_USERNAME} repo=${CIRCLE_PROJECT_REPONAME} \
              tag=${CIRCLE_TAG} ASSETS=rebar3

workflows:
  build_push:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
